version: '3.7'
services:
  ssh-chat:
    image: ghcr.io/shazow/ssh-chat:latest
    ports:
        - 2022:2022
    restart: always
    volumes:
      - ./sshchat:/sshchat
    command:
      - --verbose
      - --identity=id
      - --bind=":2022"
      - --admin=admins
      - --motd=motd
