#!/bin/ksh

daemon="/usr/local/bin/ssh-chat"
daemon_logger="daemon.info"
daemon_flags="--verbose --bind ':PORT' --identity PRIVATE_KEY --admin=ADMIN_FILE --motd=MOTD_FILE"
daemon_user="USER"

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_cmd $1

# 1. Copy this file to `/etc/rc.d` and make sure it's executable.
#    $ cp ssh-chat/examples/openbsd_service /etc/rc.d/ssh_chat
#    $ chmod +x /etc/rc.d/ssh_chat
#
# 2. Point the variable `daemon` to the executable, e.g., /usr/local/bin/ssh-chat
#    $ ln -s ~/ssh-chat/ssh-chat /usr/local/bin/ssh-chat
#
# 3. Modify the values in daemon_flags and daemon_user based on your liking.
#    Alternatively, you can delete that line and set the flags using rcctl instead:
#    $ rcctl set ssh_chat flags --verbose --bind [...] --identity [...]
#
# 4. Create the user that will run this service (see `man useradd` or `man adduser`)
#    $ useradd -m chat
#
# 5. Enable and start the service
#    $ rcctl enable ssh_chat
#    $ rcctl start ssh_chat
#
# 6. Check the logs in `/var/log/daemon`